"""Begrenzte Ausführung; API-Budget in konfigurierbaren Kosteneinheiten."""
MAX_STEPS = 20
MAX_TOOL_CALLS = 15
MAX_RETRIES_PER_STEP = 3
STEP_TIMEOUT = 60
MAX_API_CALLS_PER_TASK = 10
MAX_TOTAL_COST = 1.0
API_CALL_RESERVATION = 0.1
MAX_OUTPUT_CHARS = 24000
MAX_FILE_BYTES = 1_000_000